export const posts = [
  {
    name: "Vincent van Gogh",
    username: "vincey1853",
    location: "Zundert, Netherlands",
    avatar: "./images/avatar-vangogh.jpg",
    post: "./images/post-vangogh.jpg",
    comment: "just took a few mushrooms lol",
    likes: 21,
    avatarAlt: "Artistic avatar of Vincent van Gogh's portraits",
    postImgAlt: "Portrait of Vincent van Gogh",
  },
  {
    name: "Gustave Courbet",
    username: "gus1819",
    location: "Ornans, France",
    avatar: "./images/avatar-courbet.jpg",
    post: "./images/post-courbet.jpg",
    comment: "i'm feelin a bit stressed tbh",
    likes: 4,
    avatarAlt: "Dramatic pose by Gustave Courbet.",
    postImgAlt: "Digital adaptation of Gustave Courbet’s portrait",
  },
  {
    name: "Joseph Ducreux",
    username: "jd1735",
    location: "Paris, France",
    avatar: "./images/avatar-ducreux.jpg",
    post: "./images/post-ducreux.jpg",
    comment:
      "gm friends! which coin are YOU stacking up today?? post below and WAGMI!",
    likes: 152,
    avatarAlt: "Playful avatar of Joseph Ducreux",
    postImgAlt: "Portrait of Joseph Ducreux’s expressing his humorous style",
  },
];
